---
- name: Play for Install Nginx on WebServers
  hosts: loclhost
  gather_facts: yes
  vars:
    custom_heading: "Welcome to FirstProject"
    todays_date: "{{ ansible_facts['date_time']['date'] }}"
    host_name: "{{ ansible_facts['hostname'] }}"
    fqdn_name: "{{ ansible_facts['fqdn'] }}"
    ip_address: "{{ ansible_facts['eth0']['ipv4']['address'] }}"
  tasks:
    - name: Run Apt Update
      shell: apt update && apt install -y python-apt

     -name: Install Nginx Server
      apt:>
        name=nginx
        statue=present
      -name: Copy the files to index destination folder.
         template: >
            src=/tmp/ansibletemplatetesting/index.html
            dest=/var/www/html/index.nginx-debian.html
            owner=root
            group=root
            mode=0644
      - name: Copy the code.css files to destination folder.
         copy: >
            src=/myrepo/code.css
            dest=/var/www/html/code.css
            owner=root
            group=root
            mode=0644
      - name: Copy the javascript files to destination folder.
         copy: >
            src=/myrepo/script.js
            dest=/var/www/html/script.js
            owner=root
            group=root
            mode=0644
       - name: restart nginx
         command: service nginx restart   